LDAP_SERVER: "192.168.7.110"
LDAP_PORT: 389 
LDAP_BASE: "cn=Users,dc=futurelab,dc=intranet"
LDAP_SEARCH: "sAMAccountName={uid}"
AD_DOMAIN: "futurelab.intranet"
LDAP_ADMIN: "Administrator"
LDAP_ADMIN_PWD: "#######"
SECRET_KEY: "#######"